---

#------------------------------------------------------------------------------#
# playbook for ngGirls virtualbox
#------------------------------------------------------------------------------#

  - hosts: vm
    become: true
    roles:
      - role: ng-girls
        tags: ng-girls
      - role: ansible-role-atom-packages
        tags: apm
        become_user: "{{ default_user }}"

#------------------------------------------------------------------------------#
# playbook for ngGirls localhost
#------------------------------------------------------------------------------#

  - hosts: localhost
    become: true
    roles:
      - role: ng-girls
        tags: ng-girls
      - role: ansible-role-atom-packages
        tags: apm
        become_user: "{{ default_user }}"
