#------------------------------------------------------------------------------#
# default user
#------------------------------------------------------------------------------#

default_user: ngGirl
default_password: ngGirl

#------------------------------------------------------------------------------#
# default repositories
#------------------------------------------------------------------------------#

default_ubuntu_repositories:
  - deb http://de.archive.ubuntu.com/ubuntu xenial main restricted universe multiverse
  - deb http://de.archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse
  - deb http://de.archive.ubuntu.com/ubuntu xenial-security main restricted universe multiverse
  - deb http://de.archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse

#------------------------------------------------------------------------------#
# default packages
#------------------------------------------------------------------------------#

default_packages:
  - htop
  - iotop
  - tree
  - bmon
  - git

default_browsers:
  - firefox
  - chromium-browser

#------------------------------------------------------------------------------#
# nodejs packages
#------------------------------------------------------------------------------#

default_npm_packages:
  - "@angular/cli"

#------------------------------------------------------------------------------#
# visualstudiocode
#------------------------------------------------------------------------------#

default_visualstudiocode_plugins:
  - Angular.ng-template
  - natewallace.angular2-inline

#------------------------------------------------------------------------------#
# webstorm
#------------------------------------------------------------------------------#

default_webstorm:
  version: 2.5.0
  url: https://download.jetbrains.com/webstorm/WebStorm-2017.2.5.tar.gz
  checksum: "sha512:5e13a990ad7a56eafbd346ecc505380a3957ef67c63b524747f8f1c032d177301d2b61f9451ff7a2bca4f5b50bb3ee598d5e636e2fafcd9271a9da358452660b"

#------------------------------------------------------------------------------#
# atom plugins
#------------------------------------------------------------------------------#

atom_packages_packages:
  - angular-2
  - atom-typescript
  - emmetio/atom-plugin
  - linter
  - linter-ui-default
  - intentions
  - busy-signal

#------------------------------------------------------------------------------#
# default java debconf section for non-interactive installation
#------------------------------------------------------------------------------#

default_debconf_java8:
  - name: oracle-java8-installer
    question: oracle-java8-installer/not_exist
    vtype: error
    value: ""
  - name: oracle-java8-installer
    question: oracle-java8-installer/local
    vtype: string
    value: ""
  - name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: boolean
    value: true
  - name: oracle-java8-installer
    question: shared/present-oracle-license-v1-1
    vtype: note
    value: ""
  - name: oracle-java8-installer
    question: shared/error-oracle-license-v1-1
    vtype: error
    value: ""
