---

#------------------------------------------------------------------------------#
# add apt gpg key for visualstudiocode repository
#------------------------------------------------------------------------------#

  - name: visualstudiocode | add gpg key for visualstudiocode repository
    apt_key:
      url: https://tagplus5.github.io/vscode-ppa/ubuntu/gpg.key
      id: 2EAC63DCD08F91047ABF92ADAD2CF5D3350E178B
      state: present

#------------------------------------------------------------------------------#
# add visualstudiocode repository
#------------------------------------------------------------------------------#

  - name: visualstudiocode | add visualstudiocode repository
    apt_repository:
      repo: deb https://tagplus5.github.io/vscode-ppa/ubuntu ./
      state: present

#------------------------------------------------------------------------------#
# install visualstudiocode packages
#------------------------------------------------------------------------------#

  - name: visualstudiocode | install packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - code
      - code-insiders
    register: visualstudiocode_install

#------------------------------------------------------------------------------#
# install visualstudiocode plugins
#------------------------------------------------------------------------------#

  - name: visualstudiocode | install plugins
    shell:
      cmd: "code --install-extension {{ item }}"
    with_items:
      - "{{ default_visualstudiocode_plugins }}"
    become_user: "{{ default_user }}"
